-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 08:12:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema star_wars_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema star_wars_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `star_wars_api` DEFAULT CHARACTER SET utf8 ;
USE `star_wars_api` ;

-- -----------------------------------------------------
-- Table `star_wars_api`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `star_wars_api`.`people` (
  `idpeople` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `masa_corporal` VARCHAR(45) NULL DEFAULT NULL,
  `color_pelo` VARCHAR(45) NULL DEFAULT NULL,
  `color_ojos` VARCHAR(45) NULL DEFAULT NULL,
  `cumpleaños` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idpeople`))
ENGINE = InnoDB
AUTO_INCREMENT = 234
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `star_wars_api`.`planetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `star_wars_api`.`planetas` (
  `idplanetas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `periodo_rotacion` VARCHAR(45) NULL DEFAULT NULL,
  `periodo_orbital` VARCHAR(45) NULL DEFAULT NULL,
  `diametro` VARCHAR(45) NULL DEFAULT NULL,
  `clima` VARCHAR(45) NULL DEFAULT NULL,
  `gravedad` VARCHAR(45) NULL DEFAULT NULL,
  `terreno` VARCHAR(45) NULL DEFAULT NULL,
  `poblacion` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idplanetas`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `star_wars_api`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `star_wars_api`.`vehiculos` (
  `id_vehicuo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `fabricante` VARCHAR(45) NULL DEFAULT NULL,
  `costo_credito` VARCHAR(45) NULL DEFAULT NULL,
  `longitud` VARCHAR(45) NULL DEFAULT NULL,
  `clase_vehiculo` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_vehicuo`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

USE `star_wars_api` ;

-- -----------------------------------------------------
-- procedure createpersona
-- -----------------------------------------------------

DELIMITER $$
USE `star_wars_api`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `createpersona`(in _nombre varchar(40),in _altura varchar(40),in _masa varchar(40),in _color_pelo varchar(40),in _color_ojos
                                varchar(40),in _cumpleaños varchar(40),in _genero varchar(45),  in _url varchar(45))
BEGIN
INSERT INTO people( nombre , altura , masa_corporal , color_pelo , color_ojos , cumpleaños , genero , url )VALUES(_nombre,_altura,_masa,_color_pelo,_color_ojos,_cumpleaños,_genero, _url);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure createplaneta
-- -----------------------------------------------------

DELIMITER $$
USE `star_wars_api`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `createplaneta`(in _nombre varchar(40),in _periodo_rotacion varchar(40),
															in _perdiodo_orbitral varchar(40),in _diametro varchar(40),in _clima
                                varchar(40),in _gravedad varchar(40),in _terreno varchar(45), in _poblacion varchar(45), in _url varchar(45))
BEGIN
INSERT INTO planetas(nombre,periodo_rotacion,periodo_orbital,diametro,clima,gravedad,terreno,poblacion,url)
values(_nombre,_periodo_rotacion,_perdiodo_orbitral,_diametro,_clima,_gravedad,_terreno,_poblacion,_url);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure createvehiculos
-- -----------------------------------------------------

DELIMITER $$
USE `star_wars_api`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `createvehiculos`(in _nombre varchar(50),in _modelo varchar(45),in _fabricante varchar(45),
                                    in _costo_credito varchar(45),in _longitud varchar(45), in _clase_vehicu varchar(45),_url varchar(45))
BEGIN
INSERT INTO `star_wars_api`.`vehiculos`
(
`nombre`,
`modelo`,
`fabricante`,
`costo_credito`,
`longitud`,
`clase_vehiculo`,
`url`)
VALUES
(
_nombre,
_modelo,
_fabricante,
_costo_credito,
_longitud,
_clase_vehicu,
_url);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
